### GET request to example server
#GET http://localhost:8080/
GET https://f4f6-194-19-30-150.ngrok-free.app/

###
POST https://f4f6-194-19-30-150.ngrok-free.app/to
Content-Type: application/json

{
  "positionX": 1,
  "positionY": 1
}
